name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USER }}/trellis-api:latest .

    - name: Push to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USER }}/trellis-api:latest
